# -*- coding: utf-8 -*-
"""Assesment1_python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JtvbtjvSg8RcoUEy7Pff1B6xaVq40byx
"""

#1
len=int(input("Enter the length of rectangle: "))
wid=int(input("Enter the width of the rectangle: "))
print(f"Area of the rectangle is {len*wid}");

#2
wieght= float(input("Enter the weight in kg: "))
height= float(input("Enter the height in meter: "))
print(f"Your BMI is {round(wieght/(height**2),2)}")

#3
stu_details={}
while True:
  stu_name=input("Enter student name or end to quit program: ")
  if(stu_name.lower()=="end"):
    break;
  stu_score=input("Enter student score: ")
  stu_details[stu_name]=stu_score;

for x,y in stu_details.items():
  print(f"Student {x} is having a score of {y} ")

#4
age= int(input("Enter your age: "))
if(age<18):
  print("You are a minor")
elif(age>=18 and age<50):
  print("You are an adult")
else:
  print("You are a senior")

#5
for i in range(50):
  if(i%2==0):
    print(f"{i}, ",end="")

#6
data={}
name= input("Enter your usename: ")
psswrd= input("Enter your password: ")
data[name]=psswrd;

while True:
  temp=input("Verify your password: ")
  if(data[name]!=temp):
    print("You have entered wrong password: ")
  elif(data[name]==temp):
    print("Thank you for entering correct password! ")
    break;

#7
n= int(input("Enter number of digits you want to enter: "))
sum=0
for i in range(n):
  sum+=int(input(f"Enter your digit number {i+1} : "))

print(f"Your average of all number is {round(float(sum/n),2)}")

#8
strng= input("Enter your string: ")
vb=['a','e','i','o','u']
ans=0
for i in strng:
  if(i in vb):
    ans+=1;

print(f"Number of vowels in the string is/are: {ans}.")

#9
import datetime
print(datetime.datetime.now() )

#10
a=input("Enter number 1: ")
b=input("Enter number 2: ")
try:
  sum=int(a+b);
  print(f"Your sum is {sum}")
except:
  print("Error has occured maybe because of input datatype.")

#11
try:
  a=int(input("Enter a number: "))
  print(f"Your number is {a}")
except:
  print("You have entered incorrect datatype")

#12
from logging import exception
a=int(input("Enter 1st number: "))
b=int(input("Enter 2nd number: "))

try:
  print(f"Disvision of these 2 numbers is {a/b}")
except:
  print("Maybe you have entered a number that can't be divided.")

#13
f= open("/content/q13.txt",'w')

f.write("Hello, Python!")
print("File has been written! ")
f.close();

#14
f= open("/content/q13.txt",'r')

print(f.read())
f.close();

#15
f=open("/content/q13.txt",'a')

f.write("\nNew lines of text added! ")
print("Some lines have been appended")
f.close();
f= open("/content/q13.txt",'r')

print(f.read())
f.close();



