# -*- coding: utf-8 -*-
"""LVADSUSR108_Sairus_Q4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kA_GkcBpMpEHkegPdyb9u_wFmsiSj6y5
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.ensemble import IsolationForest

data= pd.read_csv('/content/social_network.csv')
data.head()

data.info()

data.isnull().sum() #no null values found

var_socialnetwork_df=data

plt.figure(figsize=(18, 5))
features = ['login_activity', 'posting_activity', 'social_connections']
for i, feature in enumerate(features, 1):
    plt.subplot(1, 3, i)
    sns.histplot(data=var_socialnetwork_df, x=feature, kde=True)
    plt.title(f'{feature} Distribution')
plt.tight_layout()
plt.show()

X = var_socialnetwork_df[features]

model = IsolationForest(n_estimators=100, contamination='auto', random_state=42)
predictions = model.fit_predict(X)

var_socialnetwork_df['anomaly_score'] = model.decision_function(X)
var_socialnetwork_df['is_anomaly'] = predictions
var_socialnetwork_df['is_anomaly'] = var_socialnetwork_df['is_anomaly'].apply(lambda x: 1 if x == -1 else 0)

print(var_socialnetwork_df.head())
print(var_socialnetwork_df['is_anomaly'].value_counts())

plt.figure(figsize=(10, 6))
sns.histplot(data=var_socialnetwork_df, x='anomaly_score', hue='is_anomaly', element='step', palette='viridis')
plt.title('Distribution of Anomaly Scores')
plt.xlabel('Anomaly Score')
plt.ylabel('Count')
plt.show()

from sklearn.decomposition import PCA
pca = PCA(n_components=2)
X_pca = pca.fit_transform(X)

plt.figure(figsize=(10, 6))
sns.scatterplot(x=X_pca[:, 0], y=X_pca[:, 1], hue=var_socialnetwork_df['is_anomaly'], palette='viridis', style=var_socialnetwork_df['is_anomaly'], s=100)
plt.title('Anomaly Visualization with PCA')
plt.xlabel('Principal Component 1')
plt.ylabel('Principal Component 2')
plt.legend(title='Anomaly', labels=['Normal', 'Anomaly'])
plt.show()

# PCA is not usefull but histogaram plot clearly shows anamolies

# The Isolation Forest model identifies anomalies based on deviations from typical patterns in login activity,
# posting activity, and social connections.
# Anomalies are considered to be users whose behavior significantly diverges from the norm, potentially indicating fraudulent activity.





















