# -*- coding: utf-8 -*-
"""LVADSUSR108_Sairus_Q3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WmtIymTZhUGSjR3TGJGddXF1GYHlVkbY
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
from sklearn.decomposition import PCA

data= pd.read_csv('/content/seeds.csv')
data.head()

data.info()

data.isnull().sum()

var_seeds_df=data
var_seeds_df.dropna(inplace=True)

for col in var_seeds_df.columns:
    if var_seeds_df[col].dtype == 'object' and '?' in var_seeds_df[col].unique():
        var_seeds_df = var_seeds_df[var_seeds_df[col] != '?']
    var_seeds_df[col] = pd.to_numeric(var_seeds_df[col], errors='coerce')  # Convert columns to numeric if they were object type

var_seeds_df.dropna(inplace=True)

plt.figure(figsize=(12, 8))
for i, col in enumerate(var_seeds_df.columns, 1):
    plt.subplot(3, 3, i)
    sns.histplot(var_seeds_df[col], kde=True)
    plt.title(col)
plt.tight_layout()
plt.show()

var_X = var_seeds_df.copy()
scaler = StandardScaler()
var_X_scaled = scaler.fit_transform(var_X)

inertia = []
silhouette_scores = []
range_values = range(2, 10)
for i in range_values:
    kmeans = KMeans(n_clusters=i, random_state=42)
    kmeans.fit(var_X_scaled)
    inertia.append(kmeans.inertia_)
    silhouette_scores.append(silhouette_score(var_X_scaled, kmeans.labels_))

plt.figure(figsize=(10, 4))
plt.subplot(1, 2, 1)
plt.plot(range_values, inertia, marker='o')
plt.title('Elbow Method')
plt.xlabel('Number of clusters')
plt.ylabel('Inertia')
plt.subplot(1, 2, 2)
plt.plot(range_values, silhouette_scores, marker='o')
plt.title('Silhouette Scores')
plt.xlabel('Number of clusters')
plt.ylabel('Silhouette Score')
plt.tight_layout()
plt.show()

optimal_clusters = 3
kmeans_final = KMeans(n_clusters=optimal_clusters, random_state=42)
kmeans_final.fit(var_X_scaled)

var_seeds_df['Cluster'] = kmeans_final.labels_

pca = PCA(n_components=2)
X_pca = pca.fit_transform(var_X_scaled)
sns.scatterplot(x=X_pca[:, 0], y=X_pca[:, 1], hue=kmeans_final.labels_, palette='viridis', s=100, alpha=0.6)
plt.title('Cluster Visualization with PCA')
plt.xlabel('Principal Component 1')
plt.ylabel('Principal Component 2')
plt.legend(title='Cluster')
plt.show()



